### ISSUE TITLE
5.0.6版本Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by Oner-wv** [JaxsonWang/WP-Editor.md#155]
升级到5.0.6版本后，打开网页 http://www.naodongopen.com/submission 出现了错误信息：

```bash
Fatal error: Uncaught Error: Call to undefined function Admin\get_current_screen() in /opt/lampp/htdocs/wp-content/plugins/wp-editormd/src/Admin/Controller.php:28 Stack trace: #0 /opt/lampp/htdocs/wp-content/plugins/wp-editormd/src/Admin/Controller.php(146): Admin\Controller->get_post_type() #1 /opt/lampp/htdocs/wp-includes/class-wp-hook.php(288): Admin\Controller->quicktags_settings(Array) #2 /opt/lampp/htdocs/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #3 /opt/lampp/htdocs/wp-includes/class-wp-editor.php(345): apply_filters('quicktags_setti...', Array, 'zm-content') #4 /opt/lampp/htdocs/wp-includes/class-wp-editor.php(296): _WP_Editors::editor_settings('zm-content', Array) #5 /opt/lampp/htdocs/wp-includes/general-template.php(3098): _WP_Editors::editor('', 'zm-content', Array) #6 /opt/lampp/htdocs/wp-content/themes/begin5.2/pages/template-tougao.php(169): wp_editor('', 'zm-content', Array) #7 /opt/lampp/htdocs/wp-includes/template-loader.php(74): include('/opt/lampp/htdo...') #8 /opt/lampp/htdocs/w in /opt/lampp/htdocs/wp-content/plugins/wp-editormd/src/Admin/Controller.php on line 28
```

调试信息如下：
```
系统环境	Linux
运行环境	Apache
PHP版本	7.0.27
PHP运行环境	apache2handler
Browser Information	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
WordPress版本	4.9.5
插件版本	5.0.6
jQuery版本	1.12.4
当前用户权限	administrator
WordPress地址	http://www.naodongopen.com
站点地址	http://www.naodongopen.com
常规设置	task_list => off
imagepaste => off
live_preview => on
sync_scrolling => on
html_decode => off
static_cdn => //cdn.jsdelivr.net
编辑器设置	theme_style => dark
code_style => night
语法高亮设置	highlight_mode_auto => on
line_numbers => off
highlight_library_style => coy
highlight_mode_customize => off
Emoji表情设置	support_emoji => off
文章目录设置	support_toc => off
科学公式设置	support_katex => on
流程图设置	support_flowchart => on
时序图设置	support_sequence => on
sequence_style => simple
高级设置	jquery_compatible => on
katex_compatible => off 
```

**Comment by JaxsonWang** [comment]
你这个投稿用的是插件么？

**Comment by Oner-wv** [comment]
使用的知更鸟主题默认的投稿页面。

**Comment by JaxsonWang** [comment]
关于这个我很少了解，给我点时间我去看看能不能解决吧。

你这个在后台，有没有多出专门投稿的菜单栏？类似`文章`或者`页面`的菜单栏?


![image](https://user-images.githubusercontent.com/16836692/39748046-990ad478-52e1-11e8-9ca5-32334a372856.png)

**Comment by Oner-wv** [comment]
主题会提供一个功能，新建页面后，然后选择页面模板，最后将这个页面作为投稿页。
![image](https://user-images.githubusercontent.com/10792650/39748232-1f3e1064-52e2-11e8-8b8a-85a9cf12b5e5.png)

**Comment by JaxsonWang** [comment]
那没有专门审核投稿的地方？

**Comment by Oner-wv** [comment]
投稿后的文章会和普通的文章放到一块，不过是有状态标志来区分。

**Comment by JaxsonWang** [comment]
好 下个版本解决
